### ISSUE TITLE
Add Matrix service indicator in "Services Offered" tab

### ISSUE THREAD

**Issue by gnuanu** [diasporg/Poduptime#132]
Currently lot of pods like poddery.com provide interoperability with Matrix (matrix.org) service. Please add the indicator for matrix service in th "Services Offered" tab.

**Comment by noplanman** [comment]
Extra services like that aren't really part of the federation, like the services the pods connect to directly (Facebook, Twitter, WordPress, Tumblr).
So I'm not sure if it makes sense to list those extras on podupti.me 😕 

Otherwise, taking disroot as an example, we'd have to list [all extras they offer](https://disroot.org/#_white-bar) too, which is clearly not the point here.

@dmorley  What do you think?

**Comment by dmorley** [comment]
I think if it gets added to the nodeinfo meta then it would make sense. However it's not today https://poddery.com/nodeinfo/2.0 does and can not tell us anything about matrix
