### ISSUE TITLE
language and location for go.php

### ISSUE THREAD

**Issue by dmorley** [diasporg/Poduptime#144]
Should we be thinking about language and location on go.php redirects?

**Comment by noplanman** [comment]
I guess this kind of ties in with the wizard (#145), the only problem here, is getting the prevalent language of the pod.

Because really that's what counts, right?
Even if the pod is in an English speaking country for example, if all users speak German, the language the new user would choose should be German I think.

**Comment by dmorley** [comment]
Going to close this and let the wizard or other things use the autolanguage as desired.
