### ISSUE TITLE
Please make "Location" field editable

### ISSUE THREAD

**Issue by gibberfishinc** [diasporg/Poduptime#153]
Would it be possible to make the location field editable? Our pod is located in the Netherlands but we administer it from the USA, and it has created some confusion and concern among users.

**Comment by dmorley** [comment]
Well it is automatic based on IP and the intent is to indicate where you would be connecting to the pod so you can decide if the speed would be a fit and if the laws of the land would be a fit. Since your pod is hosted in the Netherlands than I would assume the USA first amendment would not apply to your users but the laws of the Netherlands would?

**Comment by noplanman** [comment]
I agree with @dmorley, the location as it is now, is server location, not management location.

Regarding the data laws, the location of the server is important, not from where it's managed.

So as an alternative (or addition), there could be a pod note stating where the people managing the pod are from, but I think the "official" location should remain the server's home.

**Comment by dmorley** [comment]
Going to close this for now, a note in the podmin notes is the best way to address this for a podmin
